version: '2'
services:

  consul-server:
    build: consul-server
    container_name: consul-server
    hostname: consul-server
    networks:
      internal:
        ipv4_address: 172.16.1.20
    ports:
      - 8300 # Consul
      - 8301
      - 8301/udp
      - 8302
      - 8302/udp
      - 8500:8500
      - 8600:8600
      - 8600/udp  # End Consul

  mysql-master:
    image: mariadb:10.1
    container_name: mysql-master
    hostname: mysql-master
    environment:
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=my_database
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    command: mysqld --server-id=1
    volumes:
      - ./mariadb.cnf:/etc/mysql/conf.d/mariadb.cnf
    networks:
      internal:
        ipv4_address: 172.16.1.1
    ports:
      - '33006:3306'

  mysql-slave-1:
    image: mariadb:10.1
    container_name: mysql-slave-1
    hostname: mysql-slave-1
    environment:
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=my_database
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    command: mysqld --server-id=2
    volumes:
      - ./mariadb.cnf:/etc/mysql/conf.d/mariadb.cnf
    networks:
      internal:
        ipv4_address: 172.16.1.2
    ports:
      - '33007:3306'
    depends_on:
      - mysql-master

  mysql-slave-2:
    image: mariadb:10.1
    container_name: mysql-slave-2
    hostname: mysql-slave-2
    environment:
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=my_database
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    command: mysqld --server-id=3
    volumes:
      - ./mariadb.cnf:/etc/mysql/conf.d/mariadb.cnf
    networks:
      internal:
        ipv4_address: 172.16.1.3
    ports:
      - '33008:3306'
    depends_on:
      - mysql-master


  proxysql:
    build: proxysql
    container_name: proxysql
    hostname: proxysql
    ports:
      - "6032:6032"
      - "6033:6033"
      - 8300 # Consul
      - 8301
      - 8301/udp
      - 8302
      - 8302/udp
      - 8400
      - 8500
      - 8600
    networks:
      internal:
        ipv4_address: 172.16.1.30
    depends_on:
      - mysql-slave-2

  mrm:
    build: mrm
    container_name: mrm
    hostname: mrm
    ports:
      - "10001:10001"
    networks:
      internal:
        ipv4_address: 172.16.1.10
    depends_on:
      - mysql-slave-2

networks:
  internal:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv4: "true"
    ipam:
      driver: default
      config:
        - subnet: 172.16.1.0/24
          gateway: 172.16.1.254

